### ISSUE TITLE
What happened to Kiev?

### ISSUE THREAD

**Issue by timjnh** [vvo/tzdb#267]
This is more of a question than an issue.  In [this commit](https://github.com/vvo/tzdb/commit/554d731f23407c9841c9557232b57c32981fcdfe) Kiev was removed and Zaporozhye was added.  I can't see that a similar change was made in the IANA db so I'm trying to understand why the change was made.  This may be something I don't understand about the source of this data.

**Comment by maxim-yurkiv** [comment]
for me the same.
npm command "generate" which is "babel-node generate.js" shows a warning.

**Comment by valeriy-sokoloff** [comment]
Seems like IANA renamed Europe/Kiev to Europe/Kyiv (check tzdata2022c archive).
But [this](https://github.com/vvo/tzdb/commit/554d731f23407c9841c9557232b57c32981fcdfe) is a broken update, of course

**Comment by NBaruK** [comment]
Hi, 
the problem is in the version of the node (or browser). 
The `tzdb` package uses  `luxon` package for time zone validation. The `luxon` package use native [`Intl` API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) for mentioned validation. The `Kyiv` is a relatively new change.  You need the latest version of the node with the new version `Intl` API. If you run `generate` with the latest node version, the `Europe/Kyiv` time zone is presented.

@vvo, please, can you update your node version, run `generate` and push the changes?

Thank you.

**Comment by vvo** [comment]
@NBaruK I am gonna try what you just suggested, hold on

**Comment by vvo** [comment]
@NBaruK done and a release should be out shortly

**Comment by NBaruK** [comment]
Thank you very much <3.

**Comment by timjnh** [comment]
Woohoo!  Thanks guys and good find!
