### ISSUE TITLE
Grouping by country

### ISSUE THREAD

**Issue by biaspro** [vvo/tzdb#88]
Hi, this library looks great, thanks for developing and open-sourcing it!

I have a question about the "if the time zones are in the same country" rule of grouping the timezones. Would it make sense to make this rule optional? It looks like it will cut the list down significantly.

As long as the other rules are respected (daylight savings and non-DST offsets are the same), what's the purpose of grouping them by country? In Europe for example, Central European time is the same for a lot of countries, so they could be grouped and biggest cities in the group could be extracted just like they are now.

Thank you!

**Comment by vvo** [comment]
Hi there!

> what's the purpose of grouping them by country?
I took the decision that most probably if there are changes those changes will be country-wide. Let's say you group two timezones, one in the USA and one in one of the countries of south america because they have the same rules (America/Los_Angeles and America/Tijuana). It means in your database/state you'll save America/Los_Angeles for a user, even if they live in Mexico (America/Tijuana): you have to save one time zone for the user.

Then Mexico decides to change their DST rules: you won't know about this change most probably and users that selected "America/Los_Angeles" will stay in this time zone while the time will be shifting.

Hope this is clearer, let me know!
